### PR TITLE
Referencing the "shorthand" key of the JSON object instead of the "field" key.

### PR DESCRIPTION
**Pull request by Aniket-Pradhan**
I was getting an `undefined` value for `chart.encoding.color.field`, and after looking at the JSON object, I realised the key was `shorthand` instead of `field`.

Maybe, it was a typo, or it got updated over the time.

### CODE REVIEW

**Comment by sumitsg10** [comment]
yes I am trying to code

**Comment by jakevdp** [comment]
The ``shorthand`` key is not part of the schema... it is used on the Python side, and when ``to_dict()`` is called it is used to populate one or more of ``field``, ``aggregate``, ``type``, and ``timeUnit`` depending on its contents, and then is removed from the dict output.

So I don't think the matplotlib renderer needs to know about the shorthand... it just needs to know about the field.

**Comment by jakevdp** [comment]
In the end, I think the matplotlib renderer should use the dictionary output, not the class structure itself, and then this issue would resolve itself without having to duplicate shorthand parsing code.

**Comment by Aniket-Pradhan** [comment]
Well, looks like I will have to dig a bit deeper into Altair. 

I will look into the current renderer, and come up with something for MatPlotLib.

**Comment by jakevdp** [comment]
I wouldn't dig deeper in Altair, I'd just start with the vega-lite specification rather than the Altair object, and go from there

**Comment by jakevdp** [comment]
For any Altair object, the to_dict() method will return the valid vega-lite specification.

**Pull request closed without merging**
